/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module SumadorCompleto (
  input A,
  input B,
  input Cin,
  output Cout,
  output S
);
  wire s0;
  assign s0 = (A ^ B);
  assign Cout = ((A & B) | (s0 & Cin));
  assign S = (s0 ^ Cin);
endmodule
